
// This file has been generated by the GUI designer. Do not modify.
namespace earchive
{
	public partial class ViewDoc
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Toolbar toolbar1;

		private global::Gtk.HBox hbox3;

		private global::Gamma.GtkWidgets.yVBox yvboxImages;

		private global::Gtk.ScrolledWindow scrolledImages;

		private global::Gtk.VBox vboxImages;

		private global::Gamma.GtkWidgets.yProgressBar yprogressbarPrint;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Table tableProperty;

		private global::QSWidgetLib.DatePicker dateDoc;

		private global::Gtk.Entry entryNumber;

		private global::Gtk.Label label1;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label labelCreateDate;

		private global::Gtk.Label labelCreateUser;

		private global::Gtk.Label labelType;

		private global::Gtk.Label label2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textviewComments;

		private global::Gtk.Button buttonPrint;

		private global::Gtk.Button buttonPDF;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget earchive.ViewDoc
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "earchive.ViewDoc";
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.DestroyWithParent = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Internal child earchive.ViewDoc.VBox
			global::Gtk.VBox w2 = this.VBox;
			w2.Name = "dialog1_VBox";
			w2.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar1\'/></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			w2.Add(this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w2[this.toolbar1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.yvboxImages = new global::Gamma.GtkWidgets.yVBox();
			this.yvboxImages.Name = "yvboxImages";
			this.yvboxImages.Spacing = 6;
			// Container child yvboxImages.Gtk.Box+BoxChild
			this.scrolledImages = new global::Gtk.ScrolledWindow();
			this.scrolledImages.CanFocus = true;
			this.scrolledImages.Name = "scrolledImages";
			this.scrolledImages.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.scrolledImages.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledImages.Gtk.Container+ContainerChild
			global::Gtk.Viewport w4 = new global::Gtk.Viewport();
			w4.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxImages = new global::Gtk.VBox();
			this.vboxImages.Name = "vboxImages";
			this.vboxImages.Spacing = 6;
			w4.Add(this.vboxImages);
			this.scrolledImages.Add(w4);
			this.yvboxImages.Add(this.scrolledImages);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.yvboxImages[this.scrolledImages]));
			w7.Position = 0;
			// Container child yvboxImages.Gtk.Box+BoxChild
			this.yprogressbarPrint = new global::Gamma.GtkWidgets.yProgressBar();
			this.yprogressbarPrint.Name = "yprogressbarPrint";
			this.yvboxImages.Add(this.yprogressbarPrint);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.yvboxImages[this.yprogressbarPrint]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox3.Add(this.yvboxImages);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.yvboxImages]));
			w9.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.tableProperty = new global::Gtk.Table(((uint)(7)), ((uint)(2)), false);
			this.tableProperty.Name = "tableProperty";
			this.tableProperty.RowSpacing = ((uint)(6));
			this.tableProperty.ColumnSpacing = ((uint)(6));
			// Container child tableProperty.Gtk.Table+TableChild
			this.dateDoc = new global::QSWidgetLib.DatePicker();
			this.dateDoc.Events = ((global::Gdk.EventMask)(256));
			this.dateDoc.Name = "dateDoc";
			this.dateDoc.WithTime = false;
			this.dateDoc.Date = new global::System.DateTime(0);
			this.dateDoc.IsEditable = true;
			this.dateDoc.AutoSeparation = true;
			this.tableProperty.Add(this.dateDoc);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.dateDoc]));
			w10.TopAttach = ((uint)(4));
			w10.BottomAttach = ((uint)(5));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.entryNumber = new global::Gtk.Entry();
			this.entryNumber.CanFocus = true;
			this.entryNumber.Name = "entryNumber";
			this.entryNumber.IsEditable = true;
			this.entryNumber.InvisibleChar = '●';
			this.tableProperty.Add(this.entryNumber);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.entryNumber]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Тип документа:");
			this.tableProperty.Add(this.label1);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.label1]));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Номер<span foreground=\"red\">*</span>:");
			this.label3.UseMarkup = true;
			this.tableProperty.Add(this.label3);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.label3]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Дата документа<span foreground=\"red\">*</span>:");
			this.label4.UseMarkup = true;
			this.tableProperty.Add(this.label4);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.label4]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Создан:");
			this.tableProperty.Add(this.label5);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.label5]));
			w15.TopAttach = ((uint)(1));
			w15.BottomAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Пользователем:");
			this.tableProperty.Add(this.label6);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.label6]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.labelCreateDate = new global::Gtk.Label();
			this.labelCreateDate.Name = "labelCreateDate";
			this.labelCreateDate.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
			this.tableProperty.Add(this.labelCreateDate);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.labelCreateDate]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.labelCreateUser = new global::Gtk.Label();
			this.labelCreateUser.Name = "labelCreateUser";
			this.labelCreateUser.LabelProp = global::Mono.Unix.Catalog.GetString("label8");
			this.tableProperty.Add(this.labelCreateUser);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.labelCreateUser]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableProperty.Gtk.Table+TableChild
			this.labelType = new global::Gtk.Label();
			this.labelType.Name = "labelType";
			this.labelType.LabelProp = global::Mono.Unix.Catalog.GetString("Не указан");
			this.tableProperty.Add(this.labelType);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tableProperty[this.labelType]));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add(this.tableProperty);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.tableProperty]));
			w20.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Комментарии:");
			this.label2.UseMarkup = true;
			this.vbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewComments = new global::Gtk.TextView();
			this.textviewComments.CanFocus = true;
			this.textviewComments.Name = "textviewComments";
			this.GtkScrolledWindow.Add(this.textviewComments);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w23.Position = 2;
			this.hbox3.Add(this.vbox3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox3]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			w2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(w2[this.hbox3]));
			w25.Position = 1;
			// Internal child earchive.ViewDoc.ActionArea
			global::Gtk.HButtonBox w26 = this.ActionArea;
			w26.Name = "dialog1_ActionArea";
			w26.Spacing = 10;
			w26.BorderWidth = ((uint)(5));
			w26.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPrint = new global::Gtk.Button();
			this.buttonPrint.CanFocus = true;
			this.buttonPrint.Name = "buttonPrint";
			this.buttonPrint.UseUnderline = true;
			this.buttonPrint.Label = global::Mono.Unix.Catalog.GetString("Печать");
			global::Gtk.Image w27 = new global::Gtk.Image();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Menu);
			this.buttonPrint.Image = w27;
			this.AddActionWidget(this.buttonPrint, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonPrint]));
			w28.Expand = false;
			w28.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPDF = new global::Gtk.Button();
			this.buttonPDF.CanFocus = true;
			this.buttonPDF.Name = "buttonPDF";
			this.buttonPDF.UseUnderline = true;
			this.buttonPDF.Label = global::Mono.Unix.Catalog.GetString("Сохранить в PDF");
			global::Gtk.Image w29 = new global::Gtk.Image();
			w29.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("earchive.icons.page_pdf.ico");
			this.buttonPDF.Image = w29;
			w26.Add(this.buttonPDF);
			global::Gtk.ButtonBox.ButtonBoxChild w30 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonPDF]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("О_тменить");
			global::Gtk.Image w31 = new global::Gtk.Image();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w31;
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonCancel]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("_OK");
			global::Gtk.Image w33 = new global::Gtk.Image();
			w33.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-ok", global::Gtk.IconSize.Menu);
			this.buttonOk.Image = w33;
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonOk]));
			w34.Position = 3;
			w34.Expand = false;
			w34.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 708;
			this.DefaultHeight = 435;
			this.yprogressbarPrint.Hide();
			this.Show();
			this.entryNumber.Changed += new global::System.EventHandler(this.OnEntryNumberChanged);
			this.dateDoc.DateChanged += new global::System.EventHandler(this.OnDateDocDateChanged);
			this.buttonPrint.Clicked += new global::System.EventHandler(this.OnButtonPrintClicked);
			this.buttonPDF.Clicked += new global::System.EventHandler(this.OnButtonPDFClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
